### ISSUE TITLE
No Sync since Moodle 3.11+

### ISSUE THREAD

**Issue by rithmone** [LafColITS/moodle-local_ldap#27]
Since i updated to Moodle 3.11+, the sync does not create new Cohorts from LDAP-Groups.

Settings:
- Group attribute : cn
- Group class : group
- Autocreate missing cohorts : checked

Before the update the plugin worked great (3.10+)

Plugin Version: v3.7.1 / 2020110901

Kind regards

**Comment by mackensen** [comment]
We don't have explicit test coverage for auto-creating cohorts; I'll add some and see if I can replicate.

**Comment by mackensen** [comment]
I've added a test for cohort auto-creation and confirmed that they pass in Moodle 3.11.

**Comment by baumhof** [comment]
Hi there,
i got the same Problem: no cohort sync since update to 3.11
Was there some change in moodle?

Settings:
    Group attribute : memberOf
    Group class : group
    Autocreate missing cohorts : checked or unchecked doesnt matter. The Cohorts are allready created (it was working till i updatet moodle from 3.10 to 3.11 ...)

Kind regards

**Comment by danschlag** [comment]
Same on my moodle. Bug was related to the string filled in at: auth_ldap | contexts in user lookup part of ldap-server definition. This was the blocker. After changing to a proper value, the sync started working again.
