### ISSUE TITLE
Problem with synchronisation of empty LDAP groups

### ISSUE THREAD

**Issue by PhilipVien** [LafColITS/moodle-local_ldap#36]
Dear Mr. Fulton,

I hope this message finds you well. I am administering a Moodle 4.1 instance at a small school in France, and I'm using your latest version of the local_ldap plugin. However, I'm encountering an issue with it that I would like to bring to your attention.

Specifically, I'm receiving the following message repeatedly:

_PHP Notice: Undefined index: member;range=0-* in /home/agora.cfaiprovence.com/public_html/local/ldap/locallib.php on line 380
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/agora.cfaiprovence.com/public_html/local/ldap/locallib.php on line 380_

I have made some changes to the locallib.php file in an attempt to address the issue, but it seems that the code doesn't handle cases where the LDAP groups don't contain any members.

Upon further testing, I've noticed that the error message appears when the LDAP OUs are empty. So I'm wondering if you think it's possible to modify the code to handle this case.

Thank you in advance for your help, and please let me know if you require any additional information from me.

Best regards,

**Comment by djlauk** [comment]
Today I helped our IT team at our school debug and fix an issue. Our problem was based on empty groups in AD as well. In particular a tricky misunderstanding regarding range searches of multi valued LDAP attributes causes things to break.

@mackensen I am happy to submit a PR with my changes. Should I base it off main or off tag 3.7.1? (I think we are running 3.7.1 at our site.)

**Comment by mackensen** [comment]
@djlauk I think I have a candidate fix but I'd be happy to see your changes. Please base off 3.7.1.

**Comment by djlauk** [comment]
@mackensen Are you referring to the commit for #37? I had a look at that. The commit addresses the problem of the last page not being processed, but it would still break for an empty group in AD.
