### ISSUE TITLE
LDAP Pagination issue

### ISSUE THREAD

**Issue by cnapier** [LafColITS/moodle-local_ldap#37]
The plugin has been working up until a few weeks ago. I am not certain whether the recent update caused the issue or upgrading Moodle has.

Either way, I believe the issue to be with LDAP pagination. We are using Active Directory and the maxpagesize is set on AD to 5000. However the plugin seems to sync groups up until it hits our Students group (1218 members). The cohort shows 1000 users exactly and no groups after that sync, which leads me to suspect the pagination limit. 

Any advice on testing or debugging I can do to help track this down would be greatly appreciated

Thanks
Colin

**Comment by mackensen** [comment]
If you updated to v3.11.0 it introduced a problem with pagination in Active Directory and I hope to have a new release to correct that in the next few days.

**Comment by cnapier** [comment]
I had updated to 3.11.0. This is great news, happy to test and report back when the new release is out. :)

**Comment by cnapier** [comment]
I have just manually made the change and can report that our large group that was cutting off at 1000 entries is now syncing all users. Thank you for taking the time to sort this, I really appreciate it!

**Comment by mackensen** [comment]
@cnapier you're most welcome and thank you so much for manually verifying in a real environment. I'm going to re-open this until I've done a formal release.
