### ISSUE TITLE
Nested group synchronization fails if the included group has no members

### ISSUE THREAD

**Issue by raphael247** [LafColITS/moodle-local_ldap#41]
Synchronization of a nested group fails if the containing group has no members.

line: 395 in: local/ldap/locallib.php Funktion: `ldap_get_group_members_ad`

```
...
$tmp = $this->ldap_get_group_members_ad($groupcn);
if (!$tmp) {
     return false;
}
...
```
the $tmp variable will be an array with size 0.

I think, there is the same problem in function `ldap_get_group_members_rfc`

**Comment by mackensen** [comment]
@raphael247 which version of the plugin are you using? The most recent release (`v4.1.0`) contains a fix for this issue.

**Comment by raphael247** [comment]
Ups, I'm using:
$plugin->release   = 'v3.11.1';
