### ISSUE TITLE
ldap search failed with filters containing parenthesis

### ISSUE THREAD

**Issue by cperves** [LafColITS/moodle-local_ldap#9]
Hello,
I had a trouble with filters on this plugin in its version moodle_3.1_Stable
while executing \local_ldap\task\attribute_sync_task if cohortname passed to get_users_having_attribute_value contains parenthesis ldap filter failed 
I correct the trouble by replacing escaping  these parenthesis  on line 529 of /local/ldap/localib.php:
```php
'='.str_replace(')','\\29',str_replace('(','\\28',ldap_addslashes($attributevalue))).'))';
```
Hope this will be usefull
Regards,
Céline

**Comment by mackensen** [comment]
@cperves thanks for the report! I've confirmed the issue and I'm implementing a fix. I'm also going to report the issue to the core Moodle project as the problem is present in the `ldap_addslashes()` function.

**Comment by cperves** [comment]
thank you!
Regards
